### ISSUE TITLE
How to add containers? 

### ISSUE THREAD

**Issue by Syker-uk** [IAmStoxe/wirehole#49]
I am trying to add a gitea service to the docker-compose.yml: 
```
  gitea:
    image: gitea/gitea:1.15.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"  
    networks:
      private_network: 
        ipv4_address: 10.2.0.10

```
However, the container refuses to connect.

**Comment by Syker-uk** [comment]
Edit the docker-compose.yml, add the image you want to make available to the VPN and add ```network_mode: 'container:wireguard'```.

Than enable [reverse path filtering](https://www.howtouselinux.com/post/how-rp_filter-works-on-linux) and open the gitea ports on the wireguard image: 
```
services:
  gitea:
    image: gitea/gitea:1.15.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: 'container:wireguard'   #<------- this line
...
...
wireguard:
    depends_on: [unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    ...
    ...
    ports:
      - "51820:51820/udp"
      - "3000:3000"  #<-------  gitea web port
      - "22:222"        #<-------  gitea ssh port
    dns:
      - 10.2.0.100 # Points to pihole
      - 10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1 
      - net.ipv4.conf.all.rp_filter=2      #<------- enable reverse path filtering 
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3
```
The image of your choice (here, gitea) will be accessible only through the VPN at the wireguard server ip (10.6.0.1:3000).
