### ISSUE TITLE
[Pi-Hole] Adding blocking lists failed because of DNS resolution

### ISSUE THREAD

**Issue by guillaumedc** [IAmStoxe/wirehole#66]
In Pi-Hole, when I add new blocking lists and trigger «Update Gravity», it ends up on a error:
```
[✗] DNS resolution is currently unavailable
[✗] DNS resolution is not available
```
All the rest of the UI works correctly.

I used the default values of `docker-compose.yml`

```
dns:
  - 127.0.0.1
  - 10.2.0.200
[...]
environment:
  DNS1: 10.2.0.200
  DNS2: 10.2.0.200
[...]
networks:
  private_networks:
    ipv4_address: 10.2.0.100
  default:
```

Do you have an idea of where it could come from?
