### ISSUE TITLE
How to add ipv6?

### ISSUE THREAD

**Issue by KoRn0509** [IAmStoxe/wirehole#80]
How to add ipv6?

**Comment by jonny-sexton** [comment]
I managed to get this working by doing the following:

1. append `net.ipv6.conf.all.disable_ipv6=0` to wireguard.systemctls
```
  wireguard:
    depends_on: [unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles # Change to your timezone
      - SERVERPORT=51820
      #- SERVERURL=my.ddns.net #optional - For use with DDNS (Uncomment to use)
      - PEERS=1 # How many peers to generate for you (clients)
      - PEERDNS=10.2.0.100 # Set it to point to pihole
      - INTERNAL_SUBNET=10.6.0.0
      
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - 10.2.0.100 # Points to pihole
      - 10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      **-net.ipv6.conf.all.disable_ipv6=0**

    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3
```

2. then run `docker-compose up` to create the containers. Once they have been created, open a terminal in the wireguard container and run `wg-quick down wg0` to pause the server.
3. then you need to add ipv6 addresses (the addresses provided should work for everyone), and append ip6tables to PostUp and PostDown in `~/wirehole/wireguard/wg0.conf`:

```
[Interface]
Address = 10.6.0.1**, fd86:ea04:1115::1/64**
ListenPort = 51820
PrivateKey = PRIVATE_KEY
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE; **ip6tables -A FORWARD -i %i -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth+ -j MASQUERADE;**
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE; **ip6tables -D FORWARD -i %i -j ACCEPT; ip6tables -t nat -D POSTROUTING -o eth+ -j MASQUERADE;**

[Peer]
# peer1
PublicKey = PUBLIC_KEY
PresharedKey = PRESHARED_KEY
AllowedIPs = 10.6.0.2/32**, fd86:ea04:1115::2/128**

[Peer]
# peer2
PublicKey = PUBLIC_KEY
PresharedKey = PRESHARED_KEY
AllowedIPs = 10.6.0.3/32**, fd86:ea04:1115::3/128**

[Peer]
# peer3
PublicKey = PUBLIC_KEY
PresharedKey = PRESHARED_KEY
AllowedIPs = 10.6.0.4/32**, fd86:ea04:1115::4/128**
```

4. add the appropriate ipv6 address to each peer conf file like so (e.g. `~/wirehole/wireguard/peer1/peer1.conf`):
```
[Interface]
Address = 10.6.0.2, **fd86:ea04:1115::2/128**
PrivateKey = PRIVATE_KEY
ListenPort = 51820
DNS = 10.2.0.100

[Peer]
PublicKey = PUBLIC_KEY
PresharedKey = PRESHARED_KEY
Endpoint = example.duckdns.org:51820
AllowedIPs = 0.0.0.0/0, ::/0
```
5. finally start the wireguard server again, by opening a terminal in the wireguard container and running: `wg-quick up wg0`

Now you should be able to import the wireguard configs to your clients and connect to wireguard vpn over ipv6 (like from your mobile for example) :-)
