### ISSUE TITLE
Feature Request - Wireguard-UI

### ISSUE THREAD

**Issue by rdawman** [IAmStoxe/wirehole#82]
Thanks for the awesome work.

I have been trying to make the wireguard-ui work with this but somehow it's much too complicated for me.

Can somebody guide me how to integrate wireguard-ui with wirehole?

[Wireguard-UI](https://github.com/ngoduykhanh/wireguard-ui)

**Comment by ceticdev** [comment]
I am also interested in seeing if this can be integrated!

**Comment by IAmStoxe** [comment]
Test out the wg-easy branch

https://github.com/IAmStoxe/wirehole/tree/feature/wg-easy

**Comment by ceticdev** [comment]
Thanks for the update, after creating a new compose file and error is thrown:
`
$ docker-compose -p "wirehole-ui" up -d
ERROR: Missing mandatory value for "environment" option interpolating ["WG_HOST=${IP:?IP=$$(hostname -I | cut -d' ' -f1) docker compose up -d --build}", 'PASSWORD=~~~', 'WG_DEFAULT_DNS=10.2.0.100', 'WG_ALLOWED_IPS=0.0.0.0/0, ::/0'] in service "wg-easy": IP=$$(hostname -I | cut -d' ' -f1) docker compose up -d --build
`

**Comment by RhanCandia** [comment]
> Thanks for the update, after creating a new compose file and error is thrown: `$ docker-compose -p "wirehole-ui" up -d` `ERROR: Missing mandatory value for "environment" option interpolating ["WG_HOST=${IP:?IP=$$(hostname -I | cut -d' ' -f1) docker compose up -d --build}", 'PASSWORD=~~~', 'WG_DEFAULT_DNS=10.2.0.100', 'WG_ALLOWED_IPS=0.0.0.0/0, ::/0'] in service "wg-easy": IP=$$(hostname -I | cut -d' ' -f1) docker compose up -d --build`

Have you tried setting the WG_HOST variable on the docker-compose file to your server's public IP manually?

**Comment by ceticdev** [comment]
Should've put an update, I did do that and it built without errors, however I couldn't access the pihole UI and connecting as a peer made my internet stop working. Couldn't figure out why so I just reverted back to the original.

**Comment by RhanCandia** [comment]
> Should've put an update, I did do that and it built without errors, however I couldn't access the pihole UI and connecting as a peer made my internet stop working. Couldn't figure out why so I just reverted back to the original.

Oh, anyway. I haven't actually tried the new wg-easy branch of wirehole. I just went ahead and added wg-easy as another service alongside the ones already used in wirehole's main branch.

Here's how I managed to make it work.

```
version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: "mvance/unbound-rpi:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  wireguard:
    depends_on: [unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore # Change to your timezone
      - SERVERPORT=51820
      #- SERVERURL=my.ddns.net #optional - For use with DDNS (Uncomment to use)
      - PEERS=12 # How many peers to generate for you (clients)
      - PEERDNS=10.2.0.100 # Set it to point to pihole
      - INTERNAL_SUBNET=10.6.0.0

    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - 10.2.0.100 # Points to pihole
      - 10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  wg-easy:
    depends_on: [unbound, pihole]
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=<SERVER_PUBLIC_IP>
      - PASSWORD=password
      - WG_PORT=51822 # Not what port wireguard will use, this is only for the conf files that will be generated
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_ALLOWED_IP=0.0.0.0/0, ::/0 # Change this to 10.2.0.0/24 to only tunnel the web panel and DNS traffic
      - WG_DEFAULT_DNS=10.2.0.100 # Pihole
    dns:
      - 10.2.0.100 # Pihole
      - 10.2.0.200 # Unbound
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "51822:51820/udp" # Mapped 51820/udp of container to 51822 of host to run alongside wireguard at 51820
      - "51823:51821/tcp" # Mapped 51821/tcp of container to 51823 so access wg-easy panel at port 51823
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - 10.2.0.200 # Points to unbound
    environment:
      TZ: "Asia/Singapore"
      WEBPASSWORD: "" # Blank password - Can be whatever you want.
      ServerIP: 10.1.0.100 # Internal IP of pihole
      DNS1: 10.2.0.200 # Unbound IP
      DNS2: 10.2.0.200 # If we don't specify two, it will auto pick google.
    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100
```

Take note that I ran it alongside the existing services so I had to map wg-easy's wireguard port (51820) to 51822. And because of that you need to specify in the wg-easy environment that WG_PORT is 51822.

If you want wg-easy and not the wireguard service, you can just delete the entire wireguard service and appropriately change the ports that I modified in the wg-easy environment to suit your needs.
